body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! 🙏

        Please fill out the sections below to help us understand your request.

        **Before submitting:**
        - Search existing discussions to avoid duplicates
        - Vote 👍 on existing requests you support

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: 'When I try to..., I find that...'
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to solve it?
      placeholder: 'Add a command that...'
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case
      placeholder: "I'm building a SaaS app that sends..."
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: 'I tried using X but...'
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority for You
      description: How important is this feature?
      options:
        - Critical (blocking my work)
        - High (would save significant time)
        - Medium (nice to have)
        - Low (future enhancement)
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute?
      options:
        - label: I'm willing to submit a PR
        - label: I can help with testing
        - label: I can sponsor this feature
